### ISSUE TITLE
Translate raw Data to English

### ISSUE THREAD

**Issue by vamsi-bulusu** [OmdenaAI/Berlin-Chapter-Challenge-Waste-Management#5]
## Dataset Information

- Currently, the raw dataset is in German.

## To-Do List

- Convert the CSV files under the raw dataset folder to English.
- Create a new directory inside the 'data' folder for the translated dataset.

**Comment by hravat** [comment]
Working in this task

**Comment by vamsi-bulusu** [comment]
#  Translated Datasets

- Sales Packaging
- Waste Collection & Transport & Packing
- Waste Processing Facilities
- Waste Disposal Public
- Waste Generation

# Remaining Datasets

- Waste Disposal
- Hazardous Waste
